### ISSUE TITLE
Should one use this library or the one from Python's standard library?

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#130]
In GitLab by [@sinoroc](https://gitlab.com/sinoroc) on Sep 30, 2020, 10:00

This is not an issue report, it is a question. Hopefully it is acceptable to ask it here, otherwise please redirect me to the appropriate venue...

In order to avoid the _try-import-except-import dance_, I am considering simply using this library for all Python versions that my project supports (Python 3.5 to 3.8, potentially 3.9), instead of `importlib.metadata` from the standard library where available. Is that an acceptable thing to do, any drawback one should be aware of? 

On one side, one can read:

> Users of Python 3.8 and beyond are encouraged to use the standard library module. When imported on Python 3.8 and later, `importlib_metadata` replaces the DistributionFinder behavior from the stdlib, but leaves the API in tact.

-- https://importlib-metadata.readthedocs.io/en/latest/

On the other:

> This functionality is provisional and may deviate from the usual version semantics of the standard library.

-- https://docs.python.org/3/library/importlib.metadata.html

This is a bit confusing. What does that mean? What are more concretely the pros and cons of using one or the other?

Is there a way to know which version of `importlib-metadata` is in which version of Python (if that makes sense)?

**Comment by gkedge** [comment]
I want to be shmart using Python3.8 also.  Do I install importlib-metadata or not?

**Comment by FFY00** [comment]
This should be the same as https://github.com/python/importlib_resources/pull/196#issuecomment-734520374.

So I think you should check the `importlib.metadata` documentation and/or Python release notes and see if the feature you need is in the standard library or if you need to use this package which backports it.

**Comment by jaraco** [comment]
Thanks FFY00. That's right, the approach is the same. At this time of writing, most of the functionality of `importlib_metadata` is in Python 3.8. Some recent features like `dist` attribute on entry points will only appear in later Pythons (probably 3.10).

**Comment by sinoroc** [comment]
I guess the following commit also helps with this question: https://github.com/python/importlib_metadata/commit/0c86a02fbbbbdc9a888d9f2a149ec0d2cf5e7d2c
