### ISSUE TITLE
[WIP/RFC] Handle src-based distributions with egg-info installs - [opened]

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#239]
In GitLab by [@blueyed](https://gitlab.com/blueyed) on Mar 17, 2020, 12:34

_Merges fix-locate-non-wheel-editable -> master_

Ref: https://gitlab.com/python-devs/importlib_metadata/-/issues/112
Ref: https://gitlab.com/python-devs/importlib_metadata/-/issues/115

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Mar 25, 2020, 16:25

Commented on [importlib_metadata/__init__.py line 270](https://github.com/python/importlib_metadata/compare/3150ed4da9e1267d0787c6f4c1f8258a26a1dd93..5d73789b0619d5ac53dfb2966902c13b24d31e2b#diff-7df830ab27be8604ebc39a6f265b2eabL270)



Rather than undoing the abstraction here, I'd prefer if the handling of reading files for each type (distinfo, egginfo, egginfo legacy) were separate functions, such that this line of code and the subsequent return are unchanged.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Mar 25, 2020, 16:25

Commented on [importlib_metadata/__init__.py line 281](https://github.com/python/importlib_metadata/compare/3150ed4da9e1267d0787c6f4c1f8258a26a1dd93..5d73789b0619d5ac53dfb2966902c13b24d31e2b#diff-7df830ab27be8604ebc39a6f265b2eabR281)



This code could be its own method, something like `_read_files_legacy_install`. However, as I commented in #115, I'm not sure this use-case should be supported at all. Let's exclude it for now and focus on #112.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Mar 25, 2020, 16:25

Commented on [importlib_metadata/__init__.py line 521](https://github.com/python/importlib_metadata/compare/3150ed4da9e1267d0787c6f4c1f8258a26a1dd93..5d73789b0619d5ac53dfb2966902c13b24d31e2b#diff-7df830ab27be8604ebc39a6f265b2eabR521)



Can you clarify/document what `_locate_path` is intended to represent?

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Mar 25, 2020, 16:25

Commented on [importlib_metadata/__init__.py line 290](https://github.com/python/importlib_metadata/compare/3150ed4da9e1267d0787c6f4c1f8258a26a1dd93..5d73789b0619d5ac53dfb2966902c13b24d31e2b#diff-7df830ab27be8604ebc39a6f265b2eabR290)



I'd like to see the `locate_path` calculation extracted as a separate method with a docstring explaining its purpose and design. Is it possible for this behavior to be derived directly from the `package_dir` directive rather than implicitly by stumbling on the first entry in sources? This approach could fail if `file_lines[0]` happens to be missing or happens to match because the directory structure happens to match the parent directory structure.

Also, if _path is absolute, I believe this logic will traverse all the way to `/`. That seems undesirable.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Mar 25, 2020, 16:25

Commented on [importlib_metadata/__init__.py line 288](https://github.com/python/importlib_metadata/compare/3150ed4da9e1267d0787c6f4c1f8258a26a1dd93..5d73789b0619d5ac53dfb2966902c13b24d31e2b#diff-7df830ab27be8604ebc39a6f265b2eabL288)



I've always been uneasy about the egginfo support here. In particular, because `files()` is presumably meant to be "files installed by this package", but in develop mode, `files()` means "sources identified for this package" (because there are not installed files), and sources are a semantically different set of files. So this approach has always been a bit of a best-effort approach to provide something meaningful in that case. I do agree that if this support remains, it should address #112, if that can be done in a safe and reliable way.

**Comment by jaraco** [comment]
In GitLab by [@jaraco](https://gitlab.com/jaraco) on Mar 25, 2020, 16:30

Thanks @blueyed for the exploration and code. As you can see, the coverage tests are failing. The project probably should have tests for the reported issues. I suggest keeping #112 and #115 separate for now and focusing on #112 here.

Would you consider adding a test that captures #112, preferably based prior to these changes so it demonstrates the failed expectation? Let me know if you could use help on that.

This project unfortunately can't use pytest, so the test suite is a little convoluted around fixtures, but I believe there are sufficient use-cases that it shouldn't be too difficult to re-purpose some of that behavior to test a source-layout package.

**Comment by jaraco** [comment]
I'm unsure if this issue was address or remains pending. The merge request got converted to an issue during the Github migration. Please feel free to re-engage the issue if the concern remains.

**Comment by bnavigator** [comment]
I think this is still an issue:

https://github.com/abravalheri/validate-pyproject/issues/52

**Comment by jherland** [comment]
I've run into a similar issue and tried to document it (and some potential solutions) here: https://github.com/python/importlib_metadata/issues/115#issuecomment-1461103250
