### ISSUE TITLE
Drop support for Python 2.7 and 3.5

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#256]
The time has come.

**Comment by jaraco** [comment]
Fixed in #250. Released as 3.0. A maint/2.x branch is available for fixes that demand backport.

**Comment by 1000283** [comment]
You look so cool with your shades, but some of us have to deal with legacy code.

**Comment by jaraco** [comment]
This project still supports Python 2.7 and 3.5 in the maint/2.x line. Important bugs and security fixes will be applied there as appropriate, so Python 2.7/3.5 is still supported, just not in the mainline codebase and not for newer features.
