### ISSUE TITLE
Wheels for 3.x are still universal.

### ISSUE THREAD

**Issue by icemac** [python/importlib_metadata#260]
The wheels on PyPI for the 3.x releases are still universal wheels. This way they can get installed by Python 2.7 and break later on when using the code inside the wheel.
See https://pypi.org/project/importlib-metadata/3.1.0/#files

I think the following addition to `setup.cfg` could help for future releases:

```ini
[bdist_wheel]
universal = 0
```

It would be nice if the already existing wheels could be fixed, too.

**Comment by icemac** [comment]
Maybe I was a bit too fast, at least `pip-2.7` does not install a 3.x wheel.
So maybe it is only confusing for humans who see the wheel name and text next to it telling it would support Python 2.

**Comment by FFY00** [comment]
I think this can be closed as of 96c829ada0b4d3f50d563c24ec440ad704f8eb75.

**Comment by icemac** [comment]
Thank you.
