### ISSUE TITLE
Update readthedocs

### ISSUE THREAD

**Issue by therefromhere** [python/importlib_metadata#262]
Hi, could you update readthedocs - it looks like it hasn't been run 2.0? https://importlib-metadata.readthedocs.io/en/latest/changelog%20%28links%29.html

**Comment by FFY00** [comment]
@jaraco I think you need to update the upstream on RTD.

**Comment by jaraco** [comment]
I just ran the build manually and it completed fine. I think the issue is that the repo hook isn't installed.

**Comment by jaraco** [comment]
Indeed, I see "GitLab incoming webhook" installed and nothing about Github.

**Comment by jaraco** [comment]
I've added a GitHub [sic] incoming web hook and removed the GitLab one, and done the same for importlib_resources. Hopefully that resolves the issue going forward.
