### ISSUE TITLE
EntryPoints treated as sortable but not tested

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#267]
In #266, we stumbled onto a case where [flake8 sorts entry points](https://gitlab.com/pycqa/flake8/-/blob/39ceae7491f4121902a5dccc22657a0675c95539/src/flake8/plugins/manager.py#L258), adding an implicit contract on the EntryPoint class.

Assuming this project wishes to support that behavior, it should have a test to capture it directly.

**Comment by jaraco** [comment]
@asottile Can you add some background on why flake8 sorts entry points and what it expects from the sorting? In eb839a6, the tests now ensure that the entry points are sortable, but doesn't provide any guarantees on what the sorted order is. What would you expect by sorting them?

**Comment by asottile** [comment]
it does this for two reasons:

(1) startup consistency (we were seeing hard-to-debug 50/50 bugs based on plugin load order and broken monkeypatching)
(2) so that the plugins list in the `--version` output is sorted
