### ISSUE TITLE
The version field is missing from the setup.cfg metadata

### ISSUE THREAD

**Issue by mickours** [python/importlib_metadata#268]
There is currently no `version` field in the setup.cfg `[metadata]` section which leads to errors in dependencies resolution for custom packaging tools. See https://github.com/nix-community/poetry2nix/issues/123#issuecomment-742633328 

Adding the field fix the problem.

**Comment by FFY00** [comment]
This is intended behavior, your tooling is not handling this correctly. This project does not want to manually maintain a `version` field, instead it uses `setuptools_scm` to handle that automatically.
Your tooling is relying on implementation details of setuptools which are not suposed to be relied upon. I recommend you switch your tooling to use [PEP 517](https://www.python.org/dev/peps/pep-0517/).

**Comment by mickours** [comment]
Ok thanks. Indeed it seems that Poetry does not support PEP 517 for now but the work is in progress https://github.com/python-poetry/poetry/pull/2794.

Closing.
