### ISSUE TITLE
DistributionNotFound for typing-extensions with Python 3.10

### ISSUE THREAD

**Issue by williamjmorenor** [python/importlib_metadata#271]
Hello with python 3.10 alpha looks like there is a issue with the version check of importlib_metadata

'typing-extensions>=3.6.4; python_version < "3.8"' distribution was not found and is required by importlib-metadata

Look like comparing "3.10" > "3.8" is returning False in some place.

References:
 - https://github.com/pypa/twine/issues/724
 - https://github.com/pypa/build/issues/201

**Comment by FFY00** [comment]
As I said in the pypa/build issue, this looks like an issue in twine. importlib_metadata should have nothing to do with it.

**Comment by sigmavirus24** [comment]
@FFY00 You're saying twine shouldn't use `importlib_metadata`?

**Comment by layday** [comment]
No, he's saying that the issue does not originate from `importlib_metadata`.  `twine` uses `pkg_resources` to load its commands from `setuptools` entry points and `pkg_resources` for some reason attempts to validate that dependencies are met and chokes on `python_version < "3.8"` when the `python_version` is `3.10`.  The issue in `twine` could be obviated by using `importlib-metadata`, which it already depends on, to load its entry points.

**Comment by bhrutledge** [comment]
I believe this can be closed, as the underlying exception reported by Twine can be resolved by upgrading to `setuptools>=49.0.0`, as detailed at https://github.com/pypa/twine/issues/724#issuecomment-753503728.

**Comment by jaraco** [comment]
Thanks all for working through the challenges here.
