### ISSUE TITLE
Metadata returned even for superseded packages

### ISSUE THREAD

**Issue by jaraco** [python/importlib_metadata#280]
In jaraco/keyring#486, the reporter encountered an issue when keyring 22 changed the name of an entry point. After the change, with the latest version installed with `--user` and an older version installed in system site-packages, there are two copies of keyring installed, the latest version taking precedence. `importlib_metadata`, however, loads metadata for _both_ packages, including references to the unreachable and no longer valid entry points from the older package.

Probably the `entry_points` loading mechanism should only return entry points for the first package by any given name.

**Comment by gothicVI** [comment]
I'm the original reporter. Let me know if there's any information I can provide or debug I could do.
I'll happily help.

**Comment by jaraco** [comment]
In the aforementioned commit, I've started work on an implementation that appears to work. It still needs tests. However, I'm reluctant to simply roll it out because it has the potential to substantially degrade performance of loading entry points, as it requires loading and parsing the metadata for each package in order to resolve the name. I'm not sure there's a better alternative, though.
