### ISSUE TITLE
Improve efficiency of parsing requires for the case where requires.txt is present

### ISSUE THREAD

**Issue by anntzer** [python/importlib_metadata#286]
Currently, parsing "requires" is implemented as
```python
    @property
    def requires(self):
        """Generated requirements specified for this Distribution"""
        reqs = self._read_dist_info_reqs() or self._read_egg_info_reqs()
        return reqs and list(reqs)

    def _read_dist_info_reqs(self):
        return self.metadata.get_all('Requires-Dist')

    def _read_egg_info_reqs(self):
        source = self.read_text('requires.txt')
        return source and self._deps_from_requires_text(source)
```
I would like to know what are the exact expected semantics when both PKG-INFO and requires.txt are present.  Indeed, if we could choose to first read requires.txt (and skip PKG-INFO if requires.txt is present), then this could yield a many-fold speedup on accessing `dist.requires`, as parsing requires.txt is much simpler than parsing PKG-INFO (the speedup is also modulo rewriting the current parser which uses generators and regexes into a simple for loop and basic string ops).

Note that having the metadata in requires.txt and not in PKG-INFO is something that still occurs on modern systems, specifically in the case of editable installs.

**Comment by jaraco** [comment]
`PKG-INFO` is the form preferred for `dist-info` distributions. `requires.txt` is used by (legacy) `egg-info`. The only reason you get `egg-info` on editable installs is because that installation mode hasn't been updated to the preferred `dist-info` metadata.

Since `requires.txt` is a fallback for compatibility, I don't see a viable path to preferring it or avoiding the metadata costs.

**Comment by jaraco** [comment]
See also #292, where we were exploring speedup of parsing `requires.txt` and where I asked the ever-important question - is there any real-world value in addressing the use-case of performance on editable installs with egg-info?

**Comment by anntzer** [comment]
I guess it depends on whether you care about editable installs?  (Personally I use them a lot.)
I realize that perhaps editable installs should be upgraded to use dist-info, but that's a much bigger endeavour than just switching the priority between PKG-INFO and requires.txt?

**Comment by jaraco** [comment]
Sure. [I too use editable installs as a matter of course](https://github.com/jaraco/skeleton/blob/7fe4ab8294a843622d20face7f9f6ccddb2d0a14/tox.ini#L13) in development. But still I'm not sure if shaving off a few dozen milliseconds (?) during an often human interaction is worth the effort. If it's not in a tight loop or affecting a broad set of packages, the impact is tiny, even negligible, and so giving preference to the preferred metadata format (and thus consistent behavior in a world that uses that format exclusively) adds more value than the performance impact. For example, if the library gave preference to 'requires.txt', that could send a signal to package managers that they can get better performance if they write out a 'requires.txt' to a dist-info distribution to improve performance... and it would indeed improve performance, but it would be violation the intention of this library and the metadata spec.

Can you show a use-case where the performance impact is felt/noticed?

**Comment by anntzer** [comment]
IIRC there was some real-world case but I'll need a bit of time to remember what it was.

**Comment by jaraco** [comment]
I'm going to close this for now, but more than happy to re-open when there's a use case that illustrates the value of the proposed change.
