### ISSUE TITLE
Optimize regex compilation in Distribution._read_sections

### ISSUE THREAD

**Issue by tirkarthi** [python/importlib_metadata#292]
In below lines the regex pattern is compiled for each line in a loop which is not needed since we can just use `re.compile` once and use the pattern object. This improves the speed as per below benchmarks.

https://github.com/python/importlib_metadata/blob/5c9198cd8212d56db8ee9c49ee39a0980d11f5ff/importlib_metadata/__init__.py#L528-L535

Benchmark of comparing requires.txt for dask

```
$  wc requires.txt
 38  31 427 requires.txt
$ python -m pyperf timeit -s 'from importlib_metadata import Distribution; requires = open("requires.txt").read()' 'Distribution._deps_from_requires_text(requires)' -o no_pattern.json
$ python -m pyperf timeit -s 'from importlib_metadata import Distribution; requires = open("requires.txt").read()' 'Distribution._deps_from_requires_text(requires)' -o pattern.json
$ python -m pyperf compare_to no_pattern.json pattern.json --table
+-----------+------------+-----------------------+
| Benchmark | no_pattern | pattern               |
+===========+============+=======================+
| timeit    | 53.4 us    | 30.4 us: 1.76x faster |
+-----------+------------+-----------------------+
```

**Comment by jaraco** [comment]
> the regex pattern is compiled for each line

That's surprising to me. I thought regex cached these patterns.

> Benchmark of comparing requires.txt for dask

Oh, today I learned of pyperf. Thanks for the reference. I'd really like to get this functionality implemented as a 'compare against main' feature. Thanks for sharing.

**Comment by jaraco** [comment]
I note that as of 3.9, this module has two implementations of a config parser, one in the Sectioned class, and the other in the _read_sections method. Probably those should be consolidated.

**Comment by tirkarthi** [comment]
I looked into implementation n I can see the caching at https://github.com/python/cpython/blob/af50c84643ce21cfbdfdabbdfae6bd5e1368c542/Lib/re.py#L285 . It has max entries of 512. I am not sure if this is due to the way the benchmark is done in pyperf or timeit. I don't guess the cache limit is reached so still little confused by benchmark result as well.

**Comment by jaraco** [comment]
After merging #294, I set out to create a test that would capture the performance concern implied above.

As I read into the code further, I observe that this code is only reachable through legacy eggs, which are generally discouraged. Given that the code is discouraged, the performance degradation is unexpected, pyperf is [known to be unreliable](https://github.com/python/importlib_metadata/pull/294#issuecomment-808928537), and that this code is likely to be unified with the `Sectioned` class anyway, I'd respectfully like close this issue as won't fix.

If there's a real-world use-case that's impacted by this performance concern, I'll happily revisit it, but my instinct is it's not worth the trouble.
