### ISSUE TITLE
Get version from within package itself

### ISSUE THREAD

**Issue by septatrix** [python/importlib_metadata#332]
Is it currently possible to get the version from within the package itself? E.g. I have a package `foobar` which has its version in a `setup.cfg`. I do not want to manually parse that and instead would like to simply run `importlib_metadata.version("foobar")`.

The command always fails. Is support for this within the scope of this library or does it require data created during installation and I therefore have to manually parse that file? I would like to not embed the version inside the package directly as this would require a `setup.py` to read that dynamically.

**Comment by FFY00** [comment]
If the package is not actually installed, it will have no metadata directory, thus this module will not work.

> Is support for this within the scope of this library or does it require data created during installation and I therefore have to manually parse that file?

We do require metadata created during the installation, actually, the artifact generation.

> I would like to not embed the version inside the package directly as this would require a `setup.py` to read that dynamically.

That seems like the best option to me. You may also want to consider a solution such as https://github.com/pypa/setuptools_scm.

**Comment by septatrix** [comment]
Thanks for pointing me to `setuptools_scm`. That seems like a great way to automate the packaging step even further. However for now I found out about `attr:` from setuptools which allows me to save the version at only a single place but use it in the build process without resorting to `setup.py`.

**Comment by FFY00** [comment]
Oh yeah, I had forgotten about that as I don't use it 😅
