### ISSUE TITLE
No module 'typing_extensions' on Python 3.7

### ISSUE THREAD

**Issue by BKSteve** [python/importlib_metadata#352]
Previously posted here: [https://github.com/SynoCommunity/spksrc/issues/4861#issue-995639948](https://github.com/SynoCommunity/spksrc/issues/4861#issue-995639948)

Incompatibility between using Pythhon3 (3.7.11-18) and Python38 (3.8.11-4) in compiled package causes installation failure.

File 
`/var/packages/python3/target/lib/python3.7/site-packages/importlib_metadata/_compat.py`
and
`/var/packages/python38/target/lib/python3.8/site-packages/importlib_metadata/_compat.py`
both have 
```
try:
    from typing import Protocol
except ImportError:  # pragma: no cover
    """
    pytest-mypy complains here because:  error: Incompatible import of "Protocol" (imported name has type "typing_extensions._SpecialForm", local name has type "typing._SpecialForm")
    """
    from typing_extensions import Protocol
```
However Py3 typing.py
`/var/packages/python3/target/lib/python3.7/typing.py` has 
`class _Protocol(Generic, metaclass=_ProtocolMeta):` at line 1168 has underscore prefix and thus cannot be found and thus installation fails.
whereas Py38 typing.py
`/var/packages/python38/target/lib/python3.8/typing.py` has in line with _compat.py `class Protocol(Generic, metaclass=_ProtocolMeta):` is without underscore prefix in front at line 1026 is found and works for installation.

Here's my log of using installed Python 3.7.11-18
```
2021/09/14 12:52:59	Begin service_postinst
2021/09/14 12:53:00	Traceback (most recent call last):
2021/09/14 12:53:00	  File "/var/packages/python3/target/lib/python3.7/site-packages/importlib_metadata/_compat.py", line 8, in <module>
2021/09/14 12:53:00	    from typing import Protocol
2021/09/14 12:53:00	ImportError: cannot import name 'Protocol' from 'typing' (/var/packages/python3/target/lib/python3.7/typing.py)
2021/09/14 12:53:00	During handling of the above exception, another exception occurred:
2021/09/14 12:53:00	Traceback (most recent call last):
2021/09/14 12:53:00	  File "/var/packages/python3/target/bin/virtualenv", line 5, in <module>
2021/09/14 12:53:00	    from virtualenv.__main__ import run_with_catch
2021/09/14 12:53:00	  File "/var/packages/python3/target/lib/python3.7/site-packages/virtualenv/__init__.py", line 3, in <module>
2021/09/14 12:53:00	    from .run import cli_run, session_via_cli
2021/09/14 12:53:00	  File "/var/packages/python3/target/lib/python3.7/site-packages/virtualenv/run/__init__.py", line 13, in <module>
2021/09/14 12:53:00	    from .plugin.activators import ActivationSelector
2021/09/14 12:53:00	  File "/var/packages/python3/target/lib/python3.7/site-packages/virtualenv/run/plugin/activators.py", line 6, in <module>
2021/09/14 12:53:00	    from .base import ComponentBuilder
2021/09/14 12:53:00	  File "/var/packages/python3/target/lib/python3.7/site-packages/virtualenv/run/plugin/base.py", line 9, in <module>
2021/09/14 12:53:00	    from importlib_metadata import entry_points
2021/09/14 12:53:00	  File "/var/packages/python3/target/lib/python3.7/site-packages/importlib_metadata/__init__.py", line 17, in <module>
2021/09/14 12:53:00	    from . import _adapters, _meta
2021/09/14 12:53:00	  File "/var/packages/python3/target/lib/python3.7/site-packages/importlib_metadata/_meta.py", line 1, in <module>
2021/09/14 12:53:00	    from ._compat import Protocol
2021/09/14 12:53:00	  File "/var/packages/python3/target/lib/python3.7/site-packages/importlib_metadata/_compat.py", line 15, in <module>
2021/09/14 12:53:00	    from typing_extensions import Protocol  # type: ignore
2021/09/14 12:53:00	ModuleNotFoundError: No module named 'typing_extensions'
```

**Comment by jaraco** [comment]
It does indeed look like as written, "typing_extensions" is a required module on Python 3.7 and earlier.

**Comment by jaraco** [comment]
Looks like we added that change in 530f5da8dd3a255f1198f29ea0126b8b25e644d8, released in v3.2.0. I'm surprised it's only now being reported.

**Comment by jaraco** [comment]
Oh, this project _does_ [declare the dependency](https://github.com/python/importlib_metadata/blob/d03b0c305c92ac609fa69d98316d0529b69da7af/setup.cfg#L21). That explains why other users haven't encountered the issue.

@BKSteve You have an invalid install. This package has two dependencies, `zipp` and `typing-extensions` (the latter only on `python_version < "3.8"`. That's why the package works for you on your Python 3.8 install but not on your Python 3.7 install.

You need to figure out why `typing-extensions` isn't installed or isn't importable. Once you get that working, importlib_metadata should work too.

**Comment by BKSteve** [comment]
Yes, trying to work out why it is no longer loading with the python 3.7 install package.
Thanks.
