### ISSUE TITLE
differences in behavior with `pkg_resources`' `Entrypoint.load`

### ISSUE THREAD

**Issue by benoit-pierre** [python/importlib_metadata#368]
`importlib_metadata` implementation of `Entrypoint.load` does not check the requirements of the entrypoint's distribution, unlike `pkg_resources` (which raises `DistributionNotFound` if a requirement is missing, or `ContextualVersionConflict` in case of conflict). If this is expected, then that difference should at least be mentioned in the documentation, since `importlib_metadata` presents itself as a replacement for `pkg_resources`' API.

**Comment by jaraco** [comment]
I don't recall if this concern was specifically considered, but the intention was to separate concerns and simplify the implementation for the general use-case.

I would like to see some compatibility support for pkg_resources.Entrypoint.load, probably as a separate behavior not invoked by default.

I encountered this issue also when porting Setuptools' own usage of entry points from pkg_resources, requiring the [addition of these functions](https://github.com/pypa/setuptools/blob/00fbad0f93ffdba0a4d5c3f2012fd7c3de9af04d/setuptools/dist.py#L874-L896) to guarantee compatibility.

Probably most of that functionality could be ported to `EntryPoint.deps.missing`.

**Comment by jaraco** [comment]
This deficiency is now documented in the migration docs and I've also embarked on creating [jaraco/nspektr](/jaraco/nspektr) to implement the checks for entry points.
