### ISSUE TITLE
setup.py missing from files?

### ISSUE THREAD

**Issue by akiransa** [python/importlib_metadata#376]
kiraa@GBMACVCSW8354:/mnt/c/importlib_metadata-4.11.3/$ ls
CHANGES.rst  README.rst   exercises.py                         importlib_metadata.egg-info  pyproject.toml  tests
LICENSE      conftest.py  importlib_metadata                   mypy.ini                     pytest.ini      tox.ini
PKG-INFO     docs         importlib_metadata-4.11.3.dist-info  prepare                      setup.cfg

**Comment by wimglenn** [comment]
This is normal for a `pyproject.toml` based build. See [here](https://github.com/python/importlib_metadata/blob/main/pyproject.toml#L1-L3).

**Comment by G-Pereira** [comment]
Hey!
The fact that this package doesn't have a setup file makes buildroot fail to parse this package as part of the [utils/scanpypi ](https://github.com/buildroot/buildroot/blob/master/utils/scanpypi)dependency resolver. Any idea how to workaround this?

**Comment by G-Pereira** [comment]
Giving the following error.
```
buildroot package name for importlib-metadata: python-importlib-metadata
Package: python-importlib-metadata
Fetching package importlib-metadata
Downloading package importlib-metadata from https://files.pythonhosted.org/packages/3e/1d/964b27278cfa369fbe9041f604ab09c6e99556f8b7910781b4584b428c2f/importlib_metadata-4.11.3.tar.gz...
Traceback (most recent call last):
  File "/home/gpereira/Documents/octoprint-buildroot/buildroot/utils/scanpypi", line 737, in <module>
    main()
  File "/home/gpereira/Documents/octoprint-buildroot/buildroot/utils/scanpypi", line 691, in main
    package.load_setup()
  File "/home/gpereira/Documents/octoprint-buildroot/buildroot/utils/scanpypi", line 299, in load_setup
    s_file, s_path, s_desc = imp.find_module('setup', [self.tmp_extract])
  File "/usr/lib/python3.10/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'setup'
Error in sys.excepthook:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/apport_python_hook.py", line 76, in apport_excepthook
    binary = os.path.realpath(os.path.join(os.getcwd(), sys.argv[0]))
FileNotFoundError: [Errno 2] No such file or directory

Original exception was:
Traceback (most recent call last):
  File "/home/gpereira/Documents/octoprint-buildroot/buildroot/utils/scanpypi", line 737, in <module>
    main()
  File "/home/gpereira/Documents/octoprint-buildroot/buildroot/utils/scanpypi", line 691, in main
    package.load_setup()
  File "/home/gpereira/Documents/octoprint-buildroot/buildroot/utils/scanpypi", line 299, in load_setup
    s_file, s_path, s_desc = imp.find_module('setup', [self.tmp_extract])
  File "/usr/lib/python3.10/imp.py", line 297, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named 'setup'
```

**Comment by FFY00** [comment]
Yeah, I don't understand what scanpypi is exactly trying to do, but my guess is that it just not designed to work with PEP 517. Perhaps @jameshilliard could have some insights into this?

**Comment by jameshilliard** [comment]
I have a [patch pending](https://patchwork.ozlabs.org/project/buildroot/patch/20220509010917.1485280-1-james.hilliard1@gmail.com/) to deal with setuptools packages without `setup.py` for build/installation.

I also have a [patch adding flit and partial pep517 support to scanpypi](https://patchwork.ozlabs.org/project/buildroot/patch/20220313171355.271345-2-james.hilliard1@gmail.com/), I guess I probably need to also make `scanpypi` handle setuptools packages without `setup.py` but I'll probably do that after the flit support patch is merged, `scanpypi` is basically [a convenience tool for generating buildroot package definitions](https://buildroot.org/downloads/manual/manual.html#scanpypi) however they usually need to be manually tweaked in most cases anyways so it's not critical like the one handling setuptools without `setup.py` for build/install.

**Comment by jameshilliard** [comment]
Fix for build/installation [has been merged to buildroot master branch](https://github.com/buildroot/buildroot/commit/4686fb32a053753f502e24c5cd980db5b71f6a2c).

**Comment by jaraco** [comment]
Glad to hear you found a workaround. That's exactly what I would have recommended - downstream tools that are reliant on the presence of `setup.py` should stop relying on that assumption and instead follow PEP 517 build rules or patch in a shim to work around the issue.
