### ISSUE TITLE
package directory 'find_namespace:' does not exist

### ISSUE THREAD

**Issue by mansoor17syed** [python/importlib_metadata#383]
Hi Team,

When I try to create a RPM out of the package I see below error
Can you Please helm me fix it.

Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.oPH6ER
+ umask 022
+ cd /root/test_rpm_imp/CSF-PROMETHEUS/dep/BUILD
+ cd python3-importlib-metadata-4.5.0
+ python3 setup.py build
running build
running build_py
**error: package directory 'find_namespace:' does not exist
error: Bad exit status from /var/tmp/rpm-tmp.oPH6ER (%build)**

RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.oPH6ER (%build)
make: *** [Makefile:82: impdata] Error 1

**Comment by jaraco** [comment]
"find_namespace:" is a special directive to "packages" in setuptools. It's possible you have an old version of Setuptools. Other users who've reported this issue online upgraded pip. So I'd make sure you have an up-to-date Setuptools and pip and report back if you still get the error.
