### ISSUE TITLE
Suggest documenting that `packages_distributions` won't work with editable installs

### ISSUE THREAD

**Issue by layday** [python/importlib_metadata#402]
As discussed in https://github.com/pypa/packaging-problems/issues/609, PEP 660 editable wheels which are generated by backends other than setuptools will not contain a `top_level.txt` and with the `RECORD` only listing e.g. the pth file with an entry to the original package directory, `packages_distributions` will not be able to reconcile editable packages with their corresponding distributions.

**Comment by pfmoore** [comment]
A longer term alternative to simply documenting the limitation would be to standardise something equivalent to `top_level.txt`.

**Comment by Helveg** [comment]
Is there a planned solution for this being tracked anywhere?

**Comment by jaraco** [comment]
I'm not aware of one. It would require expanding the standard for editable installs to provide the necessary metadata. There's nothing importlib_metadata can do until that happens. It looks like https://github.com/pypa/packaging-problems/issues/620 already tracks a similar if not identical concern. Feel free to chime in and contribute there.
