### ISSUE TITLE
Presence of 'egg-info' metadata directory + use of virtualenv results in duplicate entry points

### ISSUE THREAD

**Issue by stephenfin** [python/importlib_metadata#410]
_(I'll preface this by saying that I think this might be similar to #101. It also feels like something that must have been reported elsewhere but my search-fu isn't sufficient to find those previous report(s))_

If a `{package}.egg-info` directory exists and you're using a virtualenv, the `importlib_metadata.distributions()` function returns a duplicate distribution. Since this function is used by `importlib_metadata.entry_points()`, you'll also see a duplicate set of entrypoints. For example, consider the following using the simplest package I could find:

```shell
❯ cd /tmp
❯ git clone https://github.com/stephenfin/clouds2env
❯ cd clouds2env
❯ virtualenv .venv
❯ source .venv/bin/activate
❯ pip install . importlib-metadata
```

```python
import importlib_metadata

for dist in importlib_metadata.distributions():
    if not dist.entry_points:
        continue
    print(dist._path)
    for ep in dist.entry_points:
        print(f'\t{ep}')
    print('***')
```

This returns something like the following:

```
clouds2env.egg-info
        EntryPoint(name='clouds2env', value='clouds2env:main', group='console_scripts')
***
/tmp/clouds2env/.venv/lib/python3.10/site-packages/clouds2env-1.1.1.dev1+g6d0ecef.dist-info
        EntryPoint(name='clouds2env', value='clouds2env:main', group='console_scripts')
***
/tmp/clouds2env/.venv/lib/python3.10/site-packages/setuptools-62.3.2.dist-info
        ... {truncated} ...
***
/tmp/clouds2env/.venv/lib/python3.10/site-packages/wheel-0.37.1.dist-info
        ... {truncated} ...
***
/tmp/clouds2env/.venv/lib/python3.10/site-packages/pip-22.1.1.dist-info
        ... {truncated} ...
```

We're not installing anything in editable mode so I think the distributions are actually the same and the info from `egg-info` should be ignore in favour of the info from the `dist-info` directory. I also see attempts to [deduplicate the returned entrypoints in `importlib_metadata.entrypoints()`](https://github.com/python/importlib_metadata/blob/009ace37032742922d5fa04c62f04cea703ade2d/importlib_metadata/__init__.py#L854) but I haven't dived into why this isn't working (or whether preventing this issue is even the goal of that code).

**Additional info**

```
❯ virtualenv --version
virtualenv 20.13.4 from /usr/lib/python3.10/site-packages/virtualenv/__init__.py
❯ pip freeze
clouds2env @ file:///tmp/clouds2env
importlib-metadata==5.0.0
PyYAML==6.0
zipp==3.8.1
❯ cat /etc/system-release
Fedora release 36 (Thirty Six)
```

**Comment by stephenfin** [comment]
Actually, no, looking at this more, I see that `importlib_metadata.entry_points()` actually is working as expected when run from the shell.

```
>>> import importlib_metadata
>>> importlib_metadata.entry_points().select(name='clouds2env')
(EntryPoint(name='clouds2env', value='clouds2env:main', group='console_scripts'),)
```

The failures I'm seeing elsewhere are when running tests via `tox`. `tox` must be doing something weird here. It does mean my reproducer above isn't actually reproducing anything. I'll close this while I try to figure out what's going on with tox.

**Comment by stephenfin** [comment]
Okay, as expected I was hitting an existing issue but it wasn't reported as an issue but rather a PR, #377. That PR was abandoned in favor of another fix, #379, which was released in [v4.12.0](https://github.com/python/importlib_metadata/releases/tag/v4.12.0) and backported to 4.11 as part of [v4.11.4](https://github.com/python/importlib_metadata/releases/tag/v4.11.4). I was seeing it on some environments (Ubuntu 20.04) and not others (Fedora 36) because `setuptools` (version 65.3.0) is vendoring `importlib_metadata` on the former and the vendored version doesn't contain this fix.

**Comment by jaraco** [comment]
I believe the best fix is to use `importlib_metadata>=4.11.4` on Python < 3.12. I think I'd intended to backport that fix in CPython versions allowing it, but it seems I didn't get to it and even Python 3.11.0 has the flawed implementation. Setuptools needs to refresh its vendored version.

**Comment by shareefj** [comment]
@jaraco @stephenfin 

I've just found my way here after a Google search for what seems like the same original issue.  In my case I'm installing an editable  Python package which seems to result in duplicate entry points.

However, I'm still seeing this with the 6.0.0 release of `importlib_metadata`.  I'm on Python 3.8.16.  Should this still be an issue?

**Comment by FFY00** [comment]
Can you show us the content of the metadata directory for your package?

**Comment by shareefj** [comment]
@FFY00 You mean the egg-info directory?

```
ll src/asic_common.egg-info/
total 32K
drwxrws--- 2 shareefj Genesee 4.0K Mar 16 13:05 .
drwxrws--- 4 shareefj Genesee 4.0K Mar 16 13:05 ..
-rw-rw---- 1 shareefj Genesee    1 Mar 16 13:05 dependency_links.txt
-rw-rw---- 1 shareefj Genesee 1.1K Mar 16 13:05 entry_points.txt
-rw-rw---- 1 shareefj Genesee  125 Mar 16 13:05 PKG-INFO
-rw-rw---- 1 shareefj Genesee  466 Mar 16 13:05 requires.txt
-rw-rw---- 1 shareefj Genesee 2.9K Mar 16 13:05 SOURCES.txt
-rw-rw---- 1 shareefj Genesee   12 Mar 16 13:05 top_level.txt
```

**Comment by jaraco** [comment]
The fix is [definitely in place](https://github.com/python/importlib_metadata/blob/5475a6e3d96e1f31441c90386e8d70514ab0e954/importlib_metadata/__init__.py#L854). Please do some more investigation on your environment or put together an (ideally minimal) reproducer and open a new issue.

Since this issue implicates "virtualenv", double-check the Setuptools version that's present in the virtualenv (or upgrade it).
