### ISSUE TITLE
Add sphinx-lint to the CI

### ISSUE THREAD

**Issue by JulienPalard** [python/importlib_metadata#412]
To avoid issues when porting to cpython, see: https://github.com/python/cpython/pull/98391#issuecomment-1296299888

[sphinx-lint](https://pypi.org/project/sphinx-lint/) in an rst linter I maintain trying as hard as possible to not raise false positives, it is drived from cpython's rstlint, and is used by cpython and Sphinx, pandas, sympy, neo4j, spyder, and probably a few other projects.

**Comment by jaraco** [comment]
Agreed - I'd like to have these checks happen here, and probably also python/importlib_resources and other projects derived from jaraco/skeleton, so probably that's the best place to employ it.

**Comment by jaraco** [comment]
I looked briefly at sphinx-lint. I figured out I can invoke it as a command. Currently, I don't have any CI support for building the docs at all. I'll probably need to add CI integration to exercise the docs builds.

**Comment by jaraco** [comment]
Added at jaraco/skeleton@82465b907d5131a57862a7242d64d610c3a05039.

**Comment by jaraco** [comment]
Fixed in 5267200.
