### ISSUE TITLE
Abstract methods in non-abstract imporlib.metadata.Distribution

### ISSUE THREAD

**Issue by busywhitespace** [python/importlib_metadata#419]
The empty methods **read_text** and **locatate_file** of **Distribution** class are decorated with _abc.abstractmethod_. But _Distribution_ class doesn't have  _metaclass=abc.ABCMeta_.

[PEP 3119](https://peps.python.org/pep-3119/), Introducing Abstract Base Classes, states.:
> The abstractmethod decorator should only be used inside a class body, and only for classes whose metaclass is (derived from) ABCMeta. 

Considering the facts that methods **read_text** and **locate_file** are used in other methods of _Distribution_ class and both are empty, only things containing are docstrings, I think the author of the class intended to use the _abstractmethod_ functionality to enforce an implementation of the aforementioned methods. So, in my opinion, the _Distribution_ class should have _metaclass=abc.ABCMeta_.

(Other possibility is that the aforementioned methods are intended as stubs. Then the _abstractmethod_ decorator may be deleted.)

I've created the PR in case the issue is right, i.e. the class should contain _metaclass=abc.ABCMeta_.

### Linked PRs
* python/cpython#100466

**Comment by jaraco** [comment]
See #422 where I'm pondering how to handle the backward compatibility concerns this change revealed.
