### ISSUE TITLE
TypeError: entry_points() got an unexpected keyword argument 'group'

### ISSUE THREAD

**Issue by hemna** [python/importlib_metadata#421]
Trying to run entry_points(group="oslo.cofig.opts") fails with 

TypeError: entry_points() got an unexpected keyword argument 'group

Documentation says group is a valid kwarg to pass in
https://docs.python.org/3/library/importlib.metadata.html#entry-points

```
└─> python --version
Python 3.9.2
└─> pip freeze |grep importlib
importlib-metadata==5.2.0
importlib-resources==5.10.1
```

I have tried with importlib-metadata==6.0.0 as well.

**Comment by jaraco** [comment]
Indeed, [entrypoints accepts kw args](https://github.com/python/importlib_metadata/blob/d3908983078a47acecf430115b2bcc2d104f54a6/importlib_metadata/__init__.py#L890). If you're getting that error, you're not actually importing `entry_points` from importlib_metadata 3.6 or later. You're probably getting `entry_points` from Python 3.9 `importlib.metadata` or maybe `importlib_metadata<3.6`.

Double-check your import. If it's `importlib_metadata`, double-check `importlib_metadata.__file__` and verify it's importing from the location where `importlib-metadata==5.2.0` is installed.
