### ISSUE TITLE
Missing Copyright Information

### ISSUE THREAD

**Issue by Andy-Grigg** [python/importlib_metadata#425]
As part of our legal process we are required to include the copyright information for each software package we use.

Before https://github.com/python/importlib_metadata/issues/387 was resolved, the copyright notice was included in the license file. However, as part of that fix the copyright notice at the top of the file was removed.

Can the copyright notice be added back in?

**Comment by jaraco** [comment]
Please see https://opensource.com/article/20/10/copyright-notices-open-source-software why maintaining a copyright notice is a nuisance. I plan to apply that principle to my other projects as well and remove the copyright notice.

Do you have any specific legal concerns?
