### ISSUE TITLE
Change build backend to flit-core?

### ISSUE THREAD

**Issue by fourtysixand2** [python/importlib_metadata#470]
With importlib_metadata and zipp now being deps of build will the backend for both change to flit-core?

Thanks

**Comment by jaraco** [comment]
I recently was reminded that [flit requires boilerplate for basic behavior](https://github.com/pypa/pyproject-hooks/pull/196#pullrequestreview-2154488050), so flit is out of the question.

I'm inclined to learn more about hatch and hatchling, which does seem to promise some of the good best practices that I desire from a build backend.

I've also recently embarked on building the [Coherent System](https://bit.ly/coherent-system), which not only provides a lot of the ergonomics of hatchling, it also requires dramatically less boilerplate (none) and has the added benefit of the essential layout, which would make it much easier to integrate the behavior into a downstream project (like CPython).
