### ISSUE TITLE
TypeError: unhashable type: 'types. SimpleNamespace'

### ISSUE THREAD

**Issue by Dolise** [python/importlib_metadata#506]
Hey!
Today I faced an issue with django autoreload when I rebuild my project.
After an hours of trying to fix that I checked list of my packages and noticed that this one was updated yesterday. After downgrade an issue had gone.
I'm not sure about reasons, but inform you 'bout that

![2024-09-12 13 21 00](https://github.com/user-attachments/assets/37c1670b-65c2-414f-a901-60b0a5ee2072)

**Comment by pjpetersik** [comment]
I also ran into this error today morning. On Stackoverflow you can find a good analysis of the problem: https://stackoverflow.com/a/78977785/10030883

In short, it is related to the monkey-patching of to `sys.modules` on the `zipp` package here:
https://github.com/jaraco/zipp/blob/d66007a66b7dbd88e69eaf59faae8b614cba256d/zipp/compat/overlay.py#L23

**Comment by jaraco** [comment]
Oh, probably the best thing to do is make sure the item that's added to `sys.modules` is hashable. I'll need to do that in the zipp project.

**Comment by jaraco** [comment]
The issue should be fixed with zipp 3.20.2, [releasing now](https://github.com/jaraco/zipp/actions/runs/10850182836).
